version: 2.1
jobs:
  docker-image:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build image"
          command: "docker build --build-arg FLUTTERVERSION=3.0.5 -t hoffmannkrzysztof/fvm-flutter:3.0.5 -t hoffmannkrzysztof/fvm-flutter:latest ."
      - run:
          name: "Push image"
          command: "docker push -a"
workflows:
  docker-image-workflow:
    jobs:
      - docker-image
